CC=gcc
CXX=g++
CXXFLAGS=-std=c++17 -g -Wall -Wextra

OBJS=crossroad-test intersect-iterator-test line-test main-test section-test tile-test trajectory-test
all: $(OBJS)

crossroad-test: crossroad-test.cpp
intersect-iterator-test: intersect-iterator-test.cpp
line-test: line-test.cpp
main-test: main-test.cpp
section-test: section-test.cpp
tile-test: tile-test.cpp
trajectory-test: trajectory-test.cpp

clean:
	rm $(OBJS)
